### ISSUE TITLE
Detect when a program is closed/minimized and set its EndTicks

### ISSUE THREAD

**Issue by ScottLilly** [ScottLilly/ActivityTracker#2]
Right now, if you close or minimize a program, and another program does not get focus, the closed/minimized program does not get an EndTicks value set.

**Comment by magentapowa** [comment]
Hello. 
I am new to open source projects and I would like to contribute.

I run the project and when no window has focus the process returned from GetActiveProcess() is File Explrorer. 
Which has no MainWindowTitle so it just returns.
I think by adding an extra check and adjusting the flow a little bit inside RecordProgramFocusSwitch() I can make it work.

Let me know what you think.

**Comment by ScottLilly** [comment]
Hi @magentapowa 

Thank you! If you have a change, please create a branch from the "dev" branch and make a pull request for it. I'm new to other people committing changes, so let me know if there are any problems creating the branch or PR.

**Comment by magentapowa** [comment]
Ok its a bit more complex than I thought. Because both 'out of focus' and 'opening a folder' returns the File Explorer process it is not so straight forward to differentiate and just ignore the one. I assume you want to log when a folder gets focus, right?

I am looking at other methods from user32.Dll like the GetWindowText(). I'll let you know if I find anything useful.

**Comment by ScottLilly** [comment]
It would be nice to detect when a folder was selected, and know which folder was selected. But, to start, I think it is OK to only record when the program is opened (or gets focused) and when it is closed, minimized, or another program is opened (or gets focus).

**Comment by ScottLilly** [comment]
@magentapowa Have you found a solution you would like to try? I think I might have found a fix today, but don't want to add it if you are almost ready to create a pull request.

**Comment by magentapowa** [comment]
No, I didnt have time at all today. Please go ahead.
